# Generated by Django 4.2.3 on 2023-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_deliveryoption_product_deliveryoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='deliveryOption',
        ),
        migrations.AddField(
            model_name='product',
            name='deliveryOption',
            field=models.ManyToManyField(blank=True, null=True, to='product.deliveryoption', verbose_name='Delivery Option'),
        ),
    ]
