# Generated by Django 4.2.3 on 2023-08-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_deliveryoption_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deliveryOption',
            field=models.ManyToManyField(blank=True, to='product.deliveryoption', verbose_name='Delivery Option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
