# Generated by Django 4.2.3 on 2024-06-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_deliveryoption_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.probrand', verbose_name='Brand'),
        ),
    ]
