# Generated by Django 4.2.3 on 2023-07-08 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=30)),
                ('symbol', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
