# Generated by Django 4.2.3 on 2023-08-14 06:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cardType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('walletBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Balance')),
                ('walletCreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('walletModifiedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('walletByUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('withdrawalAmount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Amount must be greater then 0.')], verbose_name='Amount')),
                ('withdrawalPaymentOption', models.CharField(choices=[('Bank', 'Bank'), ('PayPal', 'PayPal'), ('RazorPay', 'RazorPay')], default='Bank', max_length=255, verbose_name='Payment Option')),
                ('withdrawalMessage', models.TextField(blank=True, verbose_name='Note')),
                ('withdrawalStatus', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=255, verbose_name='Status')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modifiedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('withdrawalByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdrawal',
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('walletHistoryOfOrderId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Order ID')),
                ('walletHistoryOfOrderTransactionId', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Transaction Id')),
                ('walletHistoryOfTrackingId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tracking ID')),
                ('walletHistoryCredit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Credited')),
                ('walletHistoryDebit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Debited')),
                ('walletHistoryBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Balance')),
                ('walletHistoryCreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('walletHistoryModifiedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('walletHistoryByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.wallet', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet History',
            },
        ),
    ]
