# Generated by Django 4.2.3 on 2023-07-11 08:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bigdealapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=255, verbose_name='Title')),
                ('blogSubTitle', models.CharField(max_length=255, verbose_name='Sub Title')),
                ('blogImage', models.ImageField(upload_to='fashion/blag/blogimage', verbose_name='Image')),
                ('blogDescription', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('blogStatus', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Published or Draft')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('blogAuthor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255, verbose_name='Name')),
                ('categoryImage', models.ImageField(upload_to='fashion/blog/category', verbose_name='Image')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('commentByUser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('commentOfBlog', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bigdealapp.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blogCategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bigdealapp.blogcategory', verbose_name='Category'),
        ),
    ]
