# Generated by Django 4.2.3 on 2023-07-22 09:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigdealapp', '0003_banner_bannerimagetwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='bannerDescription',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
