# Generated by Django 4.2.3 on 2023-08-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdealapp', '0004_banner_bannerdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popularBlog',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0, verbose_name='True or False'),
        ),
    ]
