# Generated by Django 4.2.3 on 2023-09-13 08:55

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bigdealapp', '0005_blog_popularblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contactUsEmail', models.EmailField(max_length=200, verbose_name='Email')),
                ('contactUsName', models.CharField(max_length=200, verbose_name='Name')),
                ('contactUsNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Contact No.')),
                ('contactUsComment', models.TextField(max_length=255, verbose_name='Comment')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='popularBlog',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0, verbose_name='Popular Blog Or Not'),
        ),
    ]
