# Generated by Django 4.2.3 on 2023-12-12 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_alter_compare_comparebycustomer_and_more'),
        ('bigdealapp', '0007_bannertheme_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('couponCode', models.CharField(max_length=200, unique=True, verbose_name='Code')),
                ('couponType', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=255, verbose_name='Type')),
                ('numOfCoupon', models.PositiveIntegerField(default=0, verbose_name='Num. of Coupons')),
                ('couponDiscountOrFixed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Amount / Discount (%)')),
                ('minAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Minimum Amount')),
                ('expirationDateTime', models.DateTimeField(verbose_name='Expiration Date')),
                ('usageLimit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Usage Limit')),
                ('couponDescription', models.TextField(verbose_name='Description')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigdealapp.coupon', verbose_name='Coupon')),
                ('couponHistoryByOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
                ('couponHistoryByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon History',
                'verbose_name_plural': 'Coupon History',
            },
        ),
    ]
