# Generated by Django 4.2.3 on 2024-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdealapp', '0009_alter_coupon_usagelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usageLimit',
            field=models.PositiveIntegerField(default=1, verbose_name='Usage Limit'),
        ),
    ]
