# Generated by Django 4.2.3 on 2023-09-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart', verbose_name='Cart'),
        ),
    ]
